### PR TITLE
Updating the Ukrainian translation

### PR DESCRIPTION
**Pull request by spezialist1**
Updating the Ukrainian translation.

### CODE REVIEW

**Comment by samilliken** [comment]
All updates to the translations need to be made at
https://poeditor.com/projects/view?id=214887 rather than through the files
within the repo.

Scott

**Comment by samilliken** [comment]
Actually, here is the join link ->
https://poeditor.com/join/project?hash=zBX5TaqBhv

**Comment by samilliken** [comment]
Ok, I see that you joined the POEditor project, so I'll just close this merge request.

**Comment by spezialist1** [comment]
Ok, I really joined to the POEditor project and finished the Ukrainian translation to 100%.

**Pull request closed without merging**
